var testWord = [
	{
		word: "A",
		key: 0,
		partOfSpeech: undefined,
		newWord: undefined,
		flag: false,
	},
	{
		word: "depressed",
		key: 1,
		partOfSpeech: "adjective",
		newWord: undefined,
		flag: true,
	},
	{
		word: "man",
		key: 2,
		partOfSpeech: "noun",
		newWord: undefined,
		flag: true,
	},
	{
		word: "(Edward",
		key: 3,
		partOfSpeech: undefined,
		newWord: undefined,
		flag: false,
	},
	{
		word: "Norton)",
		key: 4,
		partOfSpeech: undefined,
		newWord: undefined,
		flag: false,
	},
	{
		word: "suffering",
		key: 5,
		partOfSpeech: "verb",
		newWord: undefined,
		flag: true,
	},
	{
		word: "from",
		key: 6,
		partOfSpeech: undefined,
		newWord: undefined,
		flag: false,
	},
	{
		word: "insomnia",
		key: 7,
		partOfSpeech: undefined,
		newWord: undefined,
		flag: false,
	},
	{
		word: "meets",
		key: 8,
		partOfSpeech: undefined,
		newWord: undefined,
		flag: false,
	},
	{
		word: "a",
		key: 9,
		partOfSpeech: undefined,
		newWord: undefined,
		flag: false,
	},
	{
		word: "strange",
		key: 10,
		partOfSpeech: undefined,
		newWord: undefined,
		flag: false,
	},
	{
		word: "soap",
		key: 11,
		partOfSpeech: undefined,
		newWord: undefined,
		flag: false,
	},
	{
		word: "salesman",
		key: 12,
		partOfSpeech: undefined,
		newWord: undefined,
		flag: false,
	},
	{
		word: "named",
		key: 13,
		partOfSpeech: undefined,
		newWord: undefined,
		flag: false,
	},
	{
		word: "Tyler",
		key: 14,
		partOfSpeech: undefined,
		newWord: undefined,
		flag: false,
	},
	{
		word: "Durden",
		key: 15,
		partOfSpeech: undefined,
		newWord: undefined,
		flag: false,
	},
	{
		word: "(Brad",
		key: 16,
		partOfSpeech: undefined,
		newWord: undefined,
		flag: false,
	},
	{
		word: "Pitt)",
		key: 17,
		partOfSpeech: undefined,
		newWord: undefined,
		flag: false,
	},
	{
		word: "and",
		key: 18,
		partOfSpeech: undefined,
		newWord: undefined,
		flag: false,
	},
	{
		word: "soon",
		key: 19,
		partOfSpeech: undefined,
		newWord: undefined,
		flag: false,
	},
	{
		word: "finds",
		key: 20,
		partOfSpeech: undefined,
		newWord: undefined,
		flag: false,
	},
	{
		word: "himself",
		key: 21,
		partOfSpeech: "undefined",
		newWord: undefined,
		flag: false,
	},
	{
		word: "living",
		key: 22,
		partOfSpeech: undefined,
		newWord: undefined,
		flag: false,
	},
	{
		word: "in",
		key: 23,
		partOfSpeech: undefined,
		newWord: undefined,
		flag: false,
	},
	{
		word: "his",
		key: 24,
		partOfSpeech: "undefined",
		newWord: undefined,
		flag: false,
	},
	{
		word: "squalid",
		key: 25,
		partOfSpeech: undefined,
		newWord: undefined,
		flag: false,
	},
	{
		word: "house",
		key: 26,
		partOfSpeech: undefined,
		newWord: undefined,
		flag: false,
	},
	{
		word: "after",
		key: 27,
		partOfSpeech: undefined,
		newWord: undefined,
		flag: false,
	},
	{
		word: "his",
		key: 28,
		partOfSpeech: "undefined",
		newWord: undefined,
		flag: false,
	},
	{
		word: "perfect",
		key: 29,
		partOfSpeech: undefined,
		newWord: undefined,
		flag: false,
	},
	{
		word: "apartment",
		key: 30,
		partOfSpeech: undefined,
		newWord: undefined,
		flag: false,
	},
	{
		word: "is",
		key: 31,
		partOfSpeech: undefined,
		newWord: undefined,
		flag: false,
	},
	{
		word: "destroyed",
		key: 32,
		partOfSpeech: undefined,
		newWord: undefined,
		flag: false,
	},
	{
		word: "The",
		key: 33,
		partOfSpeech: undefined,
		newWord: undefined,
		flag: false,
	},
	{
		word: "two",
		key: 34,
		partOfSpeech: undefined,
		newWord: undefined,
		flag: false,
	},
	{
		word: "bored",
		key: 35,
		partOfSpeech: undefined,
		newWord: undefined,
		flag: false,
	},
	{
		word: "men",
		key: 36,
		partOfSpeech: undefined,
		newWord: undefined,
		flag: false,
	},
	{
		word: "form",
		key: 37,
		partOfSpeech: undefined,
		newWord: undefined,
		flag: false,
	},
	{
		word: "an",
		key: 38,
		partOfSpeech: undefined,
		newWord: undefined,
		flag: false,
	},
	{
		word: "underground",
		key: 39,
		partOfSpeech: undefined,
		newWord: undefined,
		flag: false,
	},
	{
		word: "club",
		key: 40,
		partOfSpeech: undefined,
		newWord: undefined,
		flag: false,
	},
	{
		word: "with",
		key: 41,
		partOfSpeech: undefined,
		newWord: undefined,
		flag: false,
	},
	{
		word: "strict",
		key: 42,
		partOfSpeech: undefined,
		newWord: undefined,
		flag: false,
	},
	{
		word: "rules",
		key: 43,
		partOfSpeech: undefined,
		newWord: undefined,
		flag: false,
	},
	{
		word: "and",
		key: 44,
		partOfSpeech: undefined,
		newWord: undefined,
		flag: false,
	},
	{
		word: "fight",
		key: 45,
		partOfSpeech: undefined,
		newWord: undefined,
		flag: false,
	},
	{
		word: "other",
		key: 46,
		partOfSpeech: "undefined",
		newWord: undefined,
		flag: false,
	},
	{
		word: "men",
		key: 47,
		partOfSpeech: undefined,
		newWord: undefined,
		flag: false,
	},
	{
		word: "who",
		key: 48,
		partOfSpeech: "undefined",
		newWord: undefined,
		flag: false,
	},
	{
		word: "are",
		key: 49,
		partOfSpeech: undefined,
		newWord: undefined,
		flag: false,
	},
	{
		word: "fed",
		key: 50,
		partOfSpeech: undefined,
		newWord: undefined,
		flag: false,
	},
	{
		word: "up",
		key: 51,
		partOfSpeech: undefined,
		newWord: undefined,
		flag: false,
	},
	{
		word: "with",
		key: 52,
		partOfSpeech: undefined,
		newWord: undefined,
		flag: false,
	},
	{
		word: "their",
		key: 53,
		partOfSpeech: "undefined",
		newWord: undefined,
		flag: false,
	},
	{
		word: "mundane",
		key: 54,
		partOfSpeech: undefined,
		newWord: undefined,
		flag: false,
	},
	{
		word: "lives",
		key: 55,
		partOfSpeech: undefined,
		newWord: undefined,
		flag: false,
	},
	{
		word: "Their",
		key: 56,
		partOfSpeech: undefined,
		newWord: undefined,
		flag: false,
	},
	{
		word: "perfect",
		key: 57,
		partOfSpeech: undefined,
		newWord: undefined,
		flag: false,
	},
	{
		word: "partnership",
		key: 58,
		partOfSpeech: undefined,
		newWord: undefined,
		flag: false,
	},
	{
		word: "frays",
		key: 59,
		partOfSpeech: undefined,
		newWord: undefined,
		flag: false,
	},
	{
		word: "when",
		key: 60,
		partOfSpeech: undefined,
		newWord: undefined,
		flag: false,
	},
	{
		word: "Marla",
		key: 61,
		partOfSpeech: undefined,
		newWord: undefined,
		flag: false,
	},
	{
		word: "(Helena",
		key: 62,
		partOfSpeech: undefined,
		newWord: undefined,
		flag: false,
	},
	{
		word: "Bonham",
		key: 63,
		partOfSpeech: undefined,
		newWord: undefined,
		flag: false,
	},
	{
		word: "Carter)",
		key: 64,
		partOfSpeech: undefined,
		newWord: undefined,
		flag: false,
	},
	{
		word: "a",
		key: 65,
		partOfSpeech: undefined,
		newWord: undefined,
		flag: false,
	},
	{
		word: "fellow",
		key: 66,
		partOfSpeech: undefined,
		newWord: undefined,
		flag: false,
	},
	{
		word: "support",
		key: 67,
		partOfSpeech: undefined,
		newWord: undefined,
		flag: false,
	},
	{
		word: "group",
		key: 68,
		partOfSpeech: undefined,
		newWord: undefined,
		flag: false,
	},
	{
		word: "crasher",
		key: 69,
		partOfSpeech: undefined,
		newWord: undefined,
		flag: false,
	},
	{
		word: "attracts",
		key: 70,
		partOfSpeech: undefined,
		newWord: undefined,
		flag: false,
	},
	{
		word: "Tyler's",
		key: 71,
		partOfSpeech: undefined,
		newWord: undefined,
		flag: false,
	},
	{
		word: "attention",
		key: 72,
		partOfSpeech: undefined,
		newWord: undefined,
		flag: false,
	},
];
