module.exports = [
  "The Infiltrator",
  "Octopussy",
  "Office Christmas Party",
  "Of Fathers and Sons",
  "The Karate Kid",
  "Office Space",
  "Okja",
  "’Round Midnight",
  "A Bad Moms Christmas",
  "A Beautiful Day in the Neighborhood",
  "A Beautiful Mind",
  "A Bridge Too Far",
  "A Charlie Brown Christmas",
  "A Christmas Story",
  "A Civil Action",
  "A Connecticut Yankee in King Arthur's Court",
  "A Cure for Wellness",
  "A Family Man",
  "A Few Good Men",
  "A Hologram for the King",
  "A Man for All Seasons",
  "A Matter of Loaf and Death",
  "A Night at the Roxbury",
  "A Perfect Murder",
  "A Quiet Place",
  "A Shaun the Sheep Movie Farmageddon",
  "A Simple Favor",
  "A Star Is Born",
  "A Time to Kill",
  "A Very Harold & Kumar Christmas",
  "A View to a Kill",
  "A Woman Under the Influence",
  "A Wrinkle in Time",
  "A-X-",
  "A.I. Artificial Intelligence",
  "A.I. Rising",
  "Abominable",
  "Absolutely Anything",
  "Accident Man",
  "Ace in the Hole",
  "Act of Valor",
  "Active Measures",
  "Acts of Violence",
  "Ad Astra",
  "Adrift",
  "Africa The Serengeti",
  "After Hours",
  "After the Sunset",
  "Aladdin",
  "Alaska Spirit of the Wild",
  "Ali G Indahouse",
  "Alice Doesn't Live Here Anymore",
  "All That Jazz",
  "All the Money in the World",
  "Allegiant",
  "Allied",
  "Allure",
  "Alone in Berlin",
  "Alone Wolf",
  "Alpha",
  "Amadeus",
  "Amarcord",
  "Amateur Night",
  "Amazing Journeys",
  "Amazon",
  "American Assassin",
  "American Graffiti",
  "American Hangman",
  "American History X",
  "American Made",
  "American Pie",
  "American Pie 2",
  "American Pie Presents Band Camp",
  "American Pie Presents Beta House",
  "American Pie Presents The Book of Love",
  "American Pie Presents The Naked Mile",
  "American Wedding",
  "Amistad",
  "An American Tail",
  "An American Tail Fievel Goes West",
  "Anatomy of a Murder",
  "And Justice for All",
  "Angel Has Fallen",
  "Angels & Demons",
  "Annie Hall",
  "Annihilation",
  "Another American Crime",
  "Ant-Man",
  "Ant-Man and the Wasp",
  "Antarctica",
  "Antichrist",
  "Antisocial",
  "Apocalypse Now",
  "Apollo 11",
  "Aquaman",
  "Army of Shadows",
  "Arrival",
  "Arsenal",
  "Artemis Fowl",
  "Asher",
  "Assassin's Creed",
  "At Eternity's Gate",
  "Atomic Blonde",
  "Austin Found",
  "Australia Land Beyond Time",
  "Author The JT LeRoy Story",
  "Avatar",
  "Avengers Age of Ultron",
  "Avengers Endgame",
  "Avengers Infinity War",
  "Babe",
  "Babe Pig in the City",
  "Baby Driver",
  "Backdraft",
  "Backdraft 2",
  "Backstabbing for Beginners",
  "Bad Boys",
  "Bad Boys for Life",
  "Bad Boys II",
  "Bad Education",
  "Bad Times at the El Royale",
  "Bahubali The Beginning",
  "BASEketball",
  "Batman",
  "Batman & Robin",
  "Batman Assault on Arkham",
  "Batman Begins",
  "Batman Forever",
  "Batman Gotham by Gaslight",
  "Batman Ninja",
  "Batman Returns",
  "Batman The Killing Joke",
  "Batman Under the Red Hood",
  "Batman v Superman Dawn of Justice",
  "Battle of the Sexes",
  "Battleship",
  "Baywatch",
  "Beast of Burden",
  "Beauty and the Beast",
  "Beerfest",
  "Before Midnight",
  "Before Sunrise",
  "Before Sunset",
  "Behind the Candelabra",
  "Being Frank The Chris Sievey Story",
  "Being There",
  "Beirut",
  "Bent",
  "Bernadette",
  "Bert Kreischer Hey Big Boy",
  "Between Worlds",
  "Beware the Slenderman",
  "Big Hero 6",
  "Bilal A New Breed of Hero",
  "Bird",
  "Birds of a Feather II",
  "Birds of Prey (and the Fantabulous Emancipation of One Harley",
  "Black and Blue",
  "Black Dynamite",
  "Black Hawk Down",
  "Black Panther",
  "BlacKkKlansman",
  "Blade of the Immortal",
  "Blade Runner",
  "Blade Runner 2049",
  "Blame!",
  "Blinded by the Light",
  "Blindness",
  "Blockers",
  "Bloodshot",
  "Blow",
  "Blue Is the Warmest Color",
  "Bodied",
  "Body Cam",
  "Bohemian Rhapsody",
  "Boiler Room",
  "Bolt",
  "Bombshell",
  "Boogie Nights",
  "Borat Cultural Learnings of America for Make Benefit Glorious Nation of Kazakhstan",
  "Borg vs McEnroe",
  "Boxcar Bertha",
  "Boyhood",
  "Boyz n the Hood",
  "Brave",
  "Braveheart",
  "Braven",
  "Brawl in Cell Block 99",
  "Breaker Morant",
  "Breaking In",
  "Breathless",
  "Brimstone",
  "Brüno",
  "Buena Vista Social Club",
  "Bull Durham",
  "Bullet Head",
  "Bumblebee",
  "Burn After Reading",
  "Burning Sands",
  "Cabaret",
  "Cabin Fever",
  "Cameraperson",
  "Cape Fear",
  "Capone",
  "Captain America Civil War",
  "Captain America The First Avenger",
  "Captain America The Winter Soldier",
  "Captain Marvel",
  "Captain Phillips",
  "Captain Underpants The First Epic Movie",
  "Captive",
  "Carlito's Way",
  "Carriers",
  "Cars",
  "Cars 2",
  "Cars 3",
  "Cartel Land",
  "Casablanca",
  "Casino",
  "Casino Royale",
  "Cast Away",
  "Castle in the Sky",
  "Catfish",
  "Cats",
  "Central Intelligence",
  "Chappie",
  "Chapter 27",
  "Charade",
  "Charlie's Angels",
  "Charming",
  "Chasing Amy",
  "Chef",
  "Chi-Raq",
  "Chicago",
  "Chicken Run",
  "Children of Men",
  "Chinatown",
  "CHiPS",
  "Christmas Vacation 2 Cousin Eddie's Island Adventure",
  "Christmas with the Kranks",
  "Christopher Robin",
  "Chungking Express",
  "Cinderella",
  "Cinderella II Dreams Come True",
  "Cinderella III A Twist in Time",
  "Citizen Kane",
  "City Lights",
  "City of Gold",
  "City of Life and Death",
  "Clear and Present Danger",
  "Close Encounters of the Third Kind",
  "Club Dread",
  "Coco",
  "Code 46",
  "Code 8",
  "Coherence",
  "Cold Blood",
  "Cold Pursuit",
  "Collateral",
  "Collateral Beauty",
  "Colombiana",
  "Color Out of Space",
  "Compulsion",
  "Con Air",
  "Confessions of a Dangerous Mind",
  "Contagion",
  "Containment",
  "Contracted",
  "Control",
  "Cool Runnings",
  "Cooties",
  "Coral Reef Adventure",
  "Coraline",
  "Corbin Nash",
  "Cosmic Voyage",
  "Couples Retreat",
  "Cowboys & Aliens",
  "Crazy Rich Asians",
  "Creed",
  "Creed II",
  "Criminal",
  "D-Day",
  "D2 The Mighty Ducks",
  "D3 The Mighty Ducks",
  "Daddy's Home",
  "Daddy's Home 2",
  "Dallas Buyers Club",
  "Dances with Wolves",
  "Danger Close",
  "Dante's Peak",
  "Dark Phoenix",
  "Darkest Hour",
  "Date Night",
  "Dawn of the Dead",
  "Dawn of the Planet of the Apes",
  "Daybreakers",
  "Dazed and Confused",
  "Dead Presidents",
  "Deadpool",
  "Deadpool 2",
  "Dealt",
  "Dear Dictator",
  "Dear Zachary A Letter to a Son About His Father",
  "Death Proof",
  "Death Wish",
  "Death Wish 3",
  "Death Wish 4 The Crackdown",
  "Death Wish II",
  "Death Wish V The Face of Death",
  "Deepwater Horizon",
  "Defiance",
  "Deliver Us from Evil",
  "Demolition",
  "Den of Thieves",
  "Dennis the Menace",
  "Desperado",
  "Despicable Me",
  "Despicable Me 2",
  "Despicable Me 3",
  "Destination Wedding",
  "Destiny in Space",
  "Destroyer",
  "Detachment",
  "Detroit",
  "Diamonds Are Forever",
  "Die Another Day",
  "Die Hard",
  "Die Hard 2",
  "Die Hard With a Vengeance",
  "Dinosaurs Alive",
  "Dirty Dancing",
  "Dirty Grandpa",
  "Dirty Harry",
  "District 9",
  "Divergent",
  "Do the Right Thing",
  "Doctor Strange",
  "Doctor Zhivago",
  "DodgeBall A True Underdog Story",
  "Dogma",
  "Dolemite Is My Name",
  "Dolittle",
  "Dolphins",
  "Domino",
  "Don Jon",
  "Don't Cross That River",
  "Don't Let Go",
  "Double Indemnity",
  "Down in the Valley",
  "Downfall",
  "Downhill",
  "Downsizing",
  "Dr. No",
  "Dr. Strangelove or How I Learned to Stop Worrying and Love the Bomb",
  "Draft Day",
  "Dragged Across Concrete",
  "Dragon Ball Super Broly",
  "Dragon Ball Z Resurrection 'F'",
  "Drive",
  "Drone",
  "Drumline",
  "Drunk Parents",
  "Duck Soup",
  "Dude Where's My Car",
  "Due Date",
  "Dumb & Dumber",
  "Dumb and Dumber",
  "Dumb and Dumber To",
  "Dumbo",
  "Dune",
  "Dunkirk",
  "E.T. the Extra-Terrestrial",
  "Early Man",
  "East of Eden",
  "Easy Rider",
  "Eddie the Eagle",
  "Edge of Isolation",
  "Edge of Tomorrow",
  "Eighth Grade",
  "El Camino A Breaking Bad Movie",
  "El Mariachi",
  "Elf",
  "Elvis",
  "Elysium",
  "Emma.",
  "Enemy",
  "Enemy at the Gates",
  "Enemy Lines",
  "Entourage",
  "Equilibrium",
  "Erin Brockovich",
  "Ernest & Celestine",
  "Eros",
  "Escape Plan",
  "Escape Plan 2 Hades",
  "Esq.",
  "EuroTrip",
  "Everest",
  "Everybody Knows",
  "Everybody Wants Some!!",
  "Ex Machina",
  "Excalibur",
  "Experimenter",
  "Exterminator 2",
  "Extortion",
  "Extraction",
  "Extreme",
  "Eyes Without a Face",
  "He Won't Get Far on Foot",
  "How the Grinch Stole Christmas!",
  "IMAX - The Magic of Flight",
  "Inc.",
  "Jackass Presents Bad Grandpa .5",
  "Jackass Presents Bad Grandpa",
  "K.O.",
  "Kagemusha",
  "Kate Plays Christine",
  "Keanu",
  "Keeping Up with the Joneses",
  "Kelly's Heroes",
  "Kick-Ass",
  "Kick-Ass 2",
  "Kiki's Delivery Service",
  "Kill or Be Killed",
  "Kill the Messenger",
  "Killer Elite",
  "Killerman",
  "Killers Anonymous",
  "Killing Them Softly",
  "Kin",
  "King Kong",
  "King of Thieves",
  "Kingdom of Heaven",
  "Kingsman The Golden Circle",
  "Kingsman The Secret Service",
  "Kiss Kiss Bang Bang",
  "Knight and Day",
  "Knives Out",
  "Knocked Up",
  "Knowing",
  "Kodachrome",
  "Kong Skull Island",
  "Kramer vs. Kramer",
  "Kronk's New Groove",
  "Kubo and the Two Strings",
  "Kundun",
  "Kung Fu Panda",
  "Kung Fu Panda 2",
  "Kung Fu Panda 3",
  "LA 92",
  "La Bamba",
  "La Cage aux Folles",
  "La Dolce Vita",
  "La La Land",
  "La Vie en Rose",
  "Lady Bird",
  "Lars and the Real Girl",
  "Last Man Standing",
  "Last Men in Aleppo",
  "Law Abiding Citizen",
  "Lawless",
  "Lawrence of Arabia",
  "Layer Cake",
  "LBJ",
  "Leave No Trace",
  "Lee Daniels' The Butler",
  "Legend",
  "Leroy & Stitch",
  "Let's Be Cops",
  "Lethal Weapon 2",
  "Lethal Weapon 3",
  "Lethal Weapon 4",
  "Letters from Iwo Jima",
  "Liar Liar",
  "Licence to Kill",
  "Life of Brian",
  "Like Crazy",
  "Lilo & Stitch",
  "Lilo & Stitch 2 Stitch has a Glitch",
  "Limitless",
  "Lincoln",
  "Lion",
  "Little Fockers",
  "Little Giants",
  "Little Miss Sunshine",
  "Little Women",
  "Live and Let Die",
  "Live by Night",
  "Live Free or Die Hard",
  "Locke",
  "Logan",
  "Logan Lucky",
  "London Has Fallen",
  "Long Shot",
  "Long Strange Trip",
  "Looking Glass",
  "Looper",
  "Louder Than Bombs",
  "Love & Mercy",
  "Love & Other Drugs",
  "Love Actually",
  "Love Is Blind",
  "Love Liza",
  "Low Tide",
  "Lucky Number Slevin",
  "Lucy",
  "Machete",
  "Machete Kills",
  "Mad Max",
  "Mad Max 2",
  "Mad Max 2 The Road Warrior",
  "Mad Max Beyond Thunderdome",
  "Mad Max Fury Road",
  "Madagascar",
  "Madagascar 3 Europe's Most Wanted",
  "Madagascar Escape 2 Africa",
  "Magnum Force",
  "Maleficent",
  "Maleficent Mistress of Evil",
  "Mallrats",
  "Man of Steel",
  "Man of Tai Chi",
  "Man on Fire",
  "Manchester by the Sea",
  "Mandy",
  "Manhunter",
  "Mark Felt The Man Who Brought Down the White House",
  "Marriage Story",
  "Marshall",
  "Mary and Max",
  "Mary Poppins",
  "Mary Poppins Returns",
  "MASH",
  "Master and Commander The Far Side of the World",
  "Master Z The Ip Man Legacy",
  "Masterminds",
  "Matilda",
  "Mayhem",
  "Maze Runner The Death Cure",
  "Maze Runner The Scorch Trials",
  "Me and You and Everyone We Know",
  "Me Before You",
  "Mean Streets",
  "Meatballs",
  "Meatballs 4",
  "Meatballs III Summer Job",
  "Meatballs Part II",
  "Mechanic Resurrection",
  "Meet the Fockers",
  "Meet the Parents",
  "Megamind",
  "Men in Black",
  "Men in Black 3",
  "Men in Black II",
  "Men in Black International",
  "MFKZ",
  "Midnight Cowboy",
  "Midnight in Paris",
  "Midnight Sun",
  "Midnighters",
  "Midsommar",
  "Midway",
  "Mike and Dave Need Wedding Dates",
  "Mile 22",
  "Milk",
  "Mimic",
  "Minions",
  "Miracle on 34th Street",
  "Miss Bala",
  "Miss Fisher and the Crypt of Tears",
  "Missing Link",
  "Mission Impossible - Fallout",
  "Mission Impossible - Ghost Protocol",
  "Mission Impossible - Rogue Nation",
  "Mission Impossible",
  "Mission Impossible II",
  "Mission Impossible III",
  "Mission to Mir",
  "Mississippi Burning",
  "Mississippi Grind",
  "Missouri",
  "Moana",
  "Modern Times",
  "Molly's Game",
  "Mom and Dad",
  "Moms' Night Out",
  "Money Monster",
  "Money Plane",
  "Moneyball",
  "Monster Trucks",
  "Monsters University",
  "Monty Python and the Holy Grail",
  "Moon",
  "Moonlight",
  "Moonraker",
  "More American Graffiti",
  "Mortal Engines",
  "Motherless Brooklyn",
  "Mr. & Mrs. Smith",
  "Mr. Calzaghe",
  "Mr. Right",
  "Mr. Smith Goes to Washington",
  "Mr. Turner",
  "Mrs. Doubtfire",
  "Mud",
  "Mulan",
  "Mulan II",
  "Muppet Treasure Island",
  "Muppets Most Wanted",
  "Murder on the Orient Express",
  "Muriel's Wedding",
  "Mutiny on the Bounty",
  "My Beautiful Broken Brain",
  "My Best Friend's Wedding",
  "My Cousin Vinny",
  "My Fair Lady",
  "My Friend Dahmer",
  "My Little Pony The Movie",
  "My Neighbor Totoro",
  "My Neighbors the Yamadas",
  "Naked",
  "National Lampoon's Christmas Vacation",
  "National Lampoon's European Vacation",
  "National Lampoon's Vacation",
  "National Lampoon's Van Wilder",
  "National Treasure",
  "National Treasure Book of Secrets",
  "Nausicaä of the Valley of the Wind",
  "Neighbors",
  "Neighbors 2 Sorority Rising",
  "Nerve",
  "Network",
  "Never Grow Old",
  "Never Say Never Again",
  "New York",
  "Night on Earth",
  "Night School",
  "Nightcrawler",
  "Nina",
  "Ninja Assassin",
  "No Home Movie",
  "Noah",
  "Nobody Knows",
  "Non-Stop",
  "North by Northwest",
  "Not Fade Away",
  "Notorious",
  "November Criminals",
  "Novitiate",
  "Now You See Me",
  "Now You See Me 2",
  "Oblivion",
  "Obvious Child",
  "Ocean Oasis",
  "Ocean Waves",
  "Ocean's Eight",
  "Ocean's Eleven",
  "Ocean's Thirteen",
  "Ocean's Twelve",
  "Oklahoma City",
  "Old School",
  "Old Yeller",
  "Oliver & Company",
  "Olympus Has Fallen",
  "On Her Majesty's Secret Service",
  "On the Basis of Sex",
  "On the Waterfront",
  "Once Upon a Time in Mexico",
  "Once Upon a Time in Venice",
  "Once Upon a Time… in Hollywood",
  "One Flew Over the Cuckoo's Nest",
  "Only God Forgives",
  "Only the Brave",
  "Only Yesterday",
  "Onward",
  "Operation Dunkirk",
  "or the 120 Days of Sodom",
  "Orgazmo",
  "Out Cold",
  "Out of Sight",
  "Out of Time",
  "Outbreak",
  "Overboard",
  "Pacific Rim",
  "Pacific Rim Uprising",
  "Paddington",
  "Paddington 2",
  "Pain & Gain",
  "Pan",
  "Pan's Labyrinth",
  "Pandemic",
  "Panic Room",
  "Papillon",
  "Parasite",
  "Parmanu The Story of Pokhran",
  "Passengers",
  "Patch Adams",
  "Paths of Glory",
  "Patriot Games",
  "Patriots Day",
  "Patton",
  "Paul",
  "Paul Blart Mall Cop",
  "Paul Blart Mall Cop 2",
  "Paycheck",
  "PCU",
  "Peppermint",
  "Pet Sematary",
  "Pete's Dragon",
  "Peter Pan",
  "Peter Rabbit",
  "Phantom of the Paradise",
  "Philadelphia",
  "Philadelphia Experiment II",
  "Phone Booth",
  "Pineapple Express",
  "Pinocchio",
  "Pirates of the Caribbean At World's End",
  "Pirates of the Caribbean Dead Man's Chest",
  "Pirates of the Caribbean Dead Men Tell No Tales",
  "Pirates of the Caribbean On Stranger Tides",
  "Pirates of the Caribbean The Curse of the Black Pearl",
  "Pitch Black",
  "Pitch Perfect",
  "Pitch Perfect 2",
  "Pitch Perfect 3",
  "Planes",
  "Planet 51",
  "Planet Terror",
  "Platoon",
  "Playing with Fire",
  "Ploey You Never Fly Alone",
  "Pocahontas",
  "Pocahontas II Journey to a New World",
  "Point Break",
  "Pokémon Detective Pikachu",
  "Pom Poko",
  "Pontypool",
  "Ponyo",
  "Poolhall Junkies",
  "Popstar Never Stop Never Stopping",
  "Porco Rosso",
  "Portrait of a Lady on Fire",
  "Power Rangers",
  "Precious Cargo",
  "Predator",
  "Predator 2",
  "Predators",
  "Predestination",
  "Premium Rush",
  "Presenting Princess Shaw",
  "Presumed Innocent",
  "Pretty Woman",
  "Primal Fear",
  "Prince of Persia The Sands of Time",
  "Princess Mononoke",
  "Prisoners",
  "Professor Marston and the Wonder Women",
  "Proud Mary",
  "Psycho",
  "Psycho II",
  "Psycho III",
  "Psycho IV The Beginning",
  "Public Enemies",
  "Puddle Cruiser",
  "Pulp Fiction",
  "Push",
  "Quantum of Solace",
  "Quarantine",
  "Queen & Slim",
  "Queen of the Desert",
  "Quigley Down Under",
  "Quiz Show",
  "R.I.P.D.",
  "Rabid",
  "Race",
  "Radio",
  "Rage",
  "Raging Bull",
  "Raiders of the Lost Ark",
  "Ralph Breaks the Internet",
  "Rambo",
  "Rambo First Blood Part II",
  "Rambo III",
  "Rambo Last Blood",
  "Rampage",
  "Rashomon",
  "Ratatouille",
  "Ray",
  "Ready or Not",
  "Ready Player One",
  "Real Steel",
  "Rear Window",
  "Rebel Without a Cause",
  "RED",
  "RED 2",
  "Red Dawn",
  "Red Dragon",
  "Red Line",
  "Red Planet",
  "Red Sparrow",
  "Remember the Titans",
  "Renaissance Man",
  "Replicas",
  "Repo Man",
  "Repulsion",
  "Rescue Dawn",
  "Reservoir Dogs",
  "Resident Evil",
  "Resident Evil Afterlife",
  "Resident Evil Apocalypse",
  "Resident Evil Degeneration",
  "Resident Evil Extinction",
  "Resident Evil Retribution",
  "Resident Evil The Final Chapter",
  "Resident Evil Vendetta",
  "Retreat",
  "Return of the Jedi",
  "Return to Never Land",
  "Revenge of the Nerds",
  "Revenge of the Nerds II Nerds in Paradise",
  "Revenge of the Nerds III The Next Generation",
  "Revenge of the Nerds IV Nerds In Love",
  "Reversal of Fortune",
  "Riddick",
  "Ride Along",
  "Ride Along 2",
  "Rififi",
  "Rise of the Guardians",
  "Rise of the Planet of the Apes",
  "Road House",
  "Road to Perdition",
  "Road Trip",
  "Road Trip Beer Pong",
  "Robert the Bruce",
  "Robin Hood",
  "Robin Hood Men in Tights",
  "Robin Hood Prince of Thieves",
  "RoboCop",
  "RoboCop 2",
  "RoboCop 3",
  "Rock Dog",
  "Rock of Ages",
  "Rocketman",
  "RockNRolla",
  "Rocky",
  "Rogue One A Star Wars Story",
  "Roman Holiday",
  "Rounders",
  "Roxanne",
  "Rudy",
  "Runaway Jury",
  "Runner Runner",
  "Rush",
  "Salt",
  "San Andreas",
  "Saturday Night Fever",
  "Sausage Party",
  "Saved!",
  "Saving Private Ryan",
  "Say Anything...",
  "Scarface",
  "Scent of a Woman",
  "Schindler's List",
  "Scoob!",
  "Scorched Earth",
  "Scott Pilgrim Vs. The World",
  "Scrooged",
  "Search Party",
  "Searching",
  "Seconds",
  "Secretary",
  "Selena",
  "Self less",
  "Semi-Pro",
  "Serpico",
  "Seven Samurai",
  "Sex Drive",
  "Sex Tape",
  "Shaft",
  "Shakespeare in Love",
  "Shane",
  "Sharknado",
  "Shaun of the Dead",
  "Shaun the Sheep Movie",
  "Shazam!",
  "Sherlock Gnomes",
  "Sherlock The Abominable Bride",
  "Sherpa",
  "Shine a Light",
  "Shoot 'Em Up",
  "Shooter",
  "Shot Caller",
  "Shrek",
  "Shrek 2",
  "Shrek Forever After",
  "Shrek the Third",
  "Shutter Island",
  "Sicario",
  "Sicario Day of the Soldado",
  "Side Effects",
  "Sideways",
  "Silence",
  "Silencio",
  "Silver Linings Playbook",
  "Sin City",
  "Sing",
  "Singin' in the Rain",
  "Sixteen Candles",
  "Skiptrace",
  "Skyfall",
  "Skyscraper",
  "Sleeping Beauty",
  "Sleepless",
  "Sleepless in Seattle",
  "Slumdog Millionaire",
  "Small Town Crime",
  "Smallfoot",
  "Smokey and the Bandit",
  "Smokey and the Bandit II",
  "Smokey and the Bandit Part 3",
  "Smokin' Aces",
  "Smokin' Aces 2 Assassins' Ball",
  "Smurfs The Lost Village",
  "Snow White and the Seven Dwarfs",
  "Snowden",
  "Snowpiercer",
  "Solace",
  "Solo A Star Wars Story",
  "Some Like It Hot",
  "Something Wild",
  "Son of Frankenstein",
  "Song of the Sea",
  "Song to Song",
  "Sonic the Hedgehog",
  "Sorry to Bother You",
  "Space Jam",
  "Space Station 3D",
  "Spaceballs",
  "Spartan",
  "Spectral",
  "Spectre",
  "Spenser Confidential",
  "Spider-Man Far from Home",
  "Spider-Man Homecoming",
  "Spider-Man Into the Spider-Verse",
  "Spies in Disguise",
  "Spirit Stallion of the Cimarron",
  "Spirited Away",
  "Split",
  "Spotlight",
  "Spring Break",
  "Spring Breakers",
  "Spy",
  "Stagecoach",
  "Stand by Me",
  "Stand Up Guys",
  "Star Trek",
  "Star Trek Beyond",
  "Star Trek II The Wrath of Khan",
  "Star Trek Into Darkness",
  "Star Wars",
  "Star Wars Episode I - The Phantom Menace",
  "Star Wars Episode II - Attack of the Clones",
  "Star Wars Episode III - Revenge of the Sith",
  "Star Wars Episode IV - A New Hope",
  "Star Wars Episode V - The Empire Strikes Back",
  "Star Wars Episode VI - Return of the Jedi",
  "Star Wars The Force Awakens",
  "Star Wars The Last Jedi",
  "Star Wars The Rise of Skywalker",
  "Starship Troopers",
  "Starship Troopers 2 Hero of the Federation",
  "Starship Troopers 3 Marauder",
  "Starship Troopers Invasion",
  "Starship Troopers Traitor of Mars",
  "Step Brothers",
  "Steve Jobs",
  "Stigmata",
  "Still Waiting...",
  "Stitch! The Movie",
  "Stop-Loss",
  "Storks",
  "Straight Outta Compton",
  "Stranded",
  "Strange Blood",
  "Strange Magic",
  "Stuber",
  "Submergence",
  "Suburbicon",
  "Sucker Punch",
  "Sudden Impact",
  "Suicide Squad",
  "Suicide Squad Hell to Pay",
  "Sully",
  "Sunset Boulevard",
  "Super",
  "Super Speedway",
  "Super Troopers",
  "Super Troopers 2",
  "SuperFly",
  "Superman Red Son",
  "Survivor's Guide to Prison",
  "Sweet Virginia",
  "Swiss Army Man",
  "Swordfish",
  "T2 Trainspotting",
  "Tae Guk Gi The Brotherhood of War",
  "Tag",
  "Taken",
  "Taken 2",
  "Taken 3",
  "Tales from Earthsea",
  "Talladega Nights The Ballad of Ricky Bobby",
  "Tangled",
  "Tangled Before Ever After",
  "Tarzan",
  "Taxi Driver",
  "Team America World Police",
  "Tears of the Sun",
  "Ted",
  "Ted 2",
  "Teenage Mutant Ninja Turtles",
  "Teenage Mutant Ninja Turtles II The Secret of the Ooze",
  "Teenage Mutant Ninja Turtles III",
  "Teenage Mutant Ninja Turtles Out of the Shadows",
  "Term Life",
  "Terminal",
  "Termination",
  "Terminator 2 Judgment Day",
  "Terminator 3 Rise of the Machines",
  "Terminator Dark Fate",
  "Terminator Genisys",
  "Terminator Salvation",
  "Texas",
  "Thank You for Smoking",
  "Thank You for Your Service",
  "The 5th Wave",
  "The Accountant",
  "The Addams Family",
  "The Adderall Diaries",
  "The Adjustment Bureau",
  "The Adventures of Ichabod and Mr. Toad",
  "The Adventures of Tintin",
  "The Aeronauts",
  "The African Queen",
  "The Age of Innocence",
  "The Alps",
  "The Amazing Spider-Man",
  "The Amazing Spider-Man 2",
  "The American",
  "The Andromeda Strain",
  "The Angriest Man in Brooklyn",
  "The Animatrix",
  "The Apartment",
  "The Art of Self-Defense",
  "The Assignment",
  "The Assistant",
  "The Astronaut Farmer",
  "The Avengers",
  "The Aviator",
  "The Babadook",
  "the Bad and the Ugly",
  "The Bag Man",
  "The Ballad of Lefty Brown",
  "The Bank Job",
  "The Basketball Diaries",
  "The Big Heat",
  "The Big Lebowski",
  "The Big Red One",
  "The Big Short",
  "The Big Sick",
  "The Birth of a Nation",
  "The Blues Brothers",
  "The Book of Eli",
  "The Book of Life",
  "The Boondock Saints",
  "The Boondock Saints II All Saints Day",
  "The Boss",
  "The Boss Baby",
  "The Bounty Hunter",
  "The Bourne Identity",
  "The Bourne Legacy",
  "The Bourne Supremacy",
  "The Bourne Ultimatum",
  "The Boy Next Door",
  "The Boys in the Band",
  "The Brave Little Toaster",
  "The Brave Little Toaster Goes to Mars",
  "The Brave Little Toaster to the Rescue",
  "The Brave One",
  "The Breadwinner",
  "The Break-Up",
  "The Bride of Frankenstein",
  "The Bridge on the River Kwai",
  "The Brothers Grimm",
  "The Buddy Holly Story",
  "The Butler",
  "The Call of the Wild",
  "The Campaign",
  "The Cassandra Crossing",
  "The Cat in the Hat",
  "The Cat Returns",
  "The Catcher Was a Spy",
  "The Christmas Chronicles",
  "The Chronicles of Riddick Dark Fury",
  "The Circle",
  "The Clapper",
  "The Class of '92",
  "The Cloverfield Paradox",
  "The Color of Money",
  "The Commuter",
  "The Conjuring",
  "The Conjuring 2",
  "The Crazies",
  "The Da Vinci Code",
  "The Dark Knight",
  "The Dark Knight Rises",
  "The Dark Tower",
  "The Dawn Wall",
  "The Day the Earth Stood Still",
  "The Dead Pool",
  "The Death of Stalin",
  "The Deer Hunter",
  "The Departed",
  "The Devil Wears Prada",
  "The Devil's Advocate",
  "The Devil's Backbone",
  "The Dictator",
  "The Disaster Artist",
  "The Driver",
  "The Duel",
  "The DUFF",
  "The Eagle",
  "The Emoji Movie",
  "The Emperor's New Groove",
  "The Empire Strikes Back",
  "The Endless",
  "The Enforcer",
  "The Equalizer",
  "The Equalizer 2",
  "The Exception",
  "The Expendables",
  "The Expendables 2",
  "The Expendables 3",
  "The Exterminator",
  "The Fifth Estate",
  "The Flying Scotsman",
  "The Gambler",
  "The Girlfriend Experience",
  "The Grand Budapest Hotel",
  "The Great Gatsby",
  "The Guilt Trip",
  "The Hangover Part III",
  "The Hanoi Hilton",
  "The Hateful Eight",
  "The Help",
  "The Hobbit An Unexpected Journey",
  "The Hornet's Nest",
  "The Imitation Game",
  "The Intern",
  "The Internship",
  "The Kid Who Would Be King",
  "The Killing",
  "The Killing Fields",
  "The King of Comedy",
  "The King of Staten Island",
  "The Kingdom",
  "The Kitchen",
  "The Lady in the Car with Glasses and a Gun",
  "The Last Boy Scout",
  "The Last Castle",
  "The Last Full Measure",
  "The Last Man",
  "The Last Stand",
  "The Last Temptation of Christ",
  "The Last Tycoon",
  "The Last Waltz",
  "The Last Witch Hunter",
  "The League of Extraordinary Gentlemen",
  "The Legend of Hercules",
  "The Legend of Tarzan",
  "The Legion",
  "The Lego Batman Movie",
  "The Lego Movie",
  "The Lego Movie 2 The Second Part",
  "The Lego Ninjago Movie",
  "The Leopard",
  "The Life Aquatic with Steve Zissou",
  "The Lighthouse",
  "The Lincoln Lawyer",
  "The Lion Guard Return of the Roar",
  "The Lion King",
  "The Lion King 1½",
  "The Lion King 2 Simba's Pride",
  "The Little Mermaid",
  "The Little Mermaid Ariel's Beginning",
  "The Little Mermaid II Return to the Sea",
  "The Little Rascals",
  "The Little Rascals Save the Day",
  "The Living Daylights",
  "The Living Sea",
  "The Lone Ranger",
  "The Longest Day",
  "The Lost City of Z",
  "The Love Punch",
  "The Lovely Bones",
  "The Magnificent Seven",
  "The Maltese Falcon",
  "The Man from U.N.C.L.E.",
  "The Man Who Killed Hitler and Then the Bigfoot",
  "The Man Who Knew Infinity",
  "The Man with the Golden Gun",
  "The Manchurian Candidate",
  "The Martian",
  "The Mating Habits of the Earthbound Human",
  "The Matrix",
  "The Matrix Reloaded",
  "The Matrix Revolutions",
  "The Maze Runner",
  "The Mechanic",
  "The Meg",
  "The Men Who Stare at Goats",
  "The Mighty Ducks",
  "The Mine",
  "The Missing Picture",
  "The Monuments Men",
  "The Mule",
  "The Mummy",
  "The Muppet Christmas Carol",
  "The Muppet Movie",
  "The Muppets",
  "The Muppets Take Manhattan",
  "The Murder of Nicole Brown Simpson",
  "The Name of the Rose",
  "The Natural",
  "The Next Karate Kid",
  "The Next Three Days",
  "The Nice Guys",
  "The Night Before",
  "The Nightmare Before Christmas",
  "The Notebook",
  "The November Man",
  "The Nun",
  "The Nut Job",
  "The Nut Job 2 Nutty by Nature",
  "The Old Man & the Gun",
  "The Oranges",
  "The Other Boleyn Girl",
  "The Other Guys",
  "The Other Woman",
  "The Outlaw Josey Wales",
  "The Outpost",
  "The Overnighters",
  "The Paper Chase",
  "The Parent Trap",
  "The Parts You Lose",
  "The Peanut Butter Falcon",
  "The Peanuts Movie",
  "The Pelican Brief",
  "The Perfect Storm",
  "The Philadelphia Experiment",
  "The Philadelphia Story",
  "The Pianist",
  "The Players Club",
  "The Polar Express",
  "The Post",
  "The Predator",
  "The Prestige",
  "The Princess and the Frog",
  "The Princess Bride",
  "The Proposal",
  "The Purge",
  "The Purge Anarchy",
  "The Purge Election Year",
  "The Quake",
  "The Raid",
  "The Raid 2",
  "The Raid Redemption",
  "The Railway Man",
  "The Rainmaker",
  "The Red Turtle",
  "The Replacements",
  "The Rescuers",
  "The Rescuers Down Under",
  "The Revenant",
  "The Rhythm Section",
  "The Right Stuff",
  "The Road to El Dorado",
  "The Rock",
  "The Rocketeer",
  "The Rum Diary",
  "The Running Man",
  "The Sandlot",
  "The Santa Clause",
  "The Scent of Rain & Lightning",
  "The Searchers",
  "The Secret Life of Pets",
  "The Secret Life of Pets 2",
  "The Secret World of Arrietty",
  "The Seventh Seal",
  "The Shape of Water",
  "The Shawshank Redemption",
  "The Signal",
  "The Silence of the Lambs",
  "The Sisters Brothers",
  "The Slammin' Salmon",
  "The Smurfs",
  "The Smurfs 2",
  "The Son of Kong",
  "The Sound of Music",
  "The Space Between Us",
  "The Spy Who Dumped Me",
  "The Spy Who Loved Me",
  "The Square",
  "The Stanford Prison Experiment",
  "The Sum of All Fears",
  "The Sun Is Also a Star",
  "The Sword of Doom",
  "The Tailor of Panama",
  "The Taking of Pelham 1 2 3",
  "The Tale of the Princess Kaguya",
  "The Talented Mr. Ripley",
  "The Terminator",
  "The Thin Blue Line",
  "The Thin Red Line",
  "The Thing",
  "The Thinning",
  "The Third Man",
  "The Thirteenth Floor",
  "The Thomas Crown Affair",
  "The Three Musketeers",
  "The Town",
  "The Transporter",
  "The Transporter Refueled",
  "The Treasure of the Sierra Madre",
  "The Triplets of Belleville",
  "The Trust",
  "The Two Popes",
  "The Untouchables",
  "The Upside",
  "The Usual Suspects",
  "The Verdict",
  "The Vow",
  "The Warriors",
  "The Waterboy",
  "The Wave",
  "The Way Back",
  "The Wedding Ringer",
  "The Wedding Singer",
  "The Wicker Man",
  "The Wiggles Cold Spaghetti Western",
  "The Wiggles Dance Party",
  "The Wiggles Hoop-Dee-Doo!",
  "The Wiggles Live Hot Potatoes!",
  "The Wiggles Movie",
  "The Wiggles Sailing Around the World",
  "The Wild Bunch",
  "The Wild One",
  "The Wind Rises",
  "The Wizard of Oz",
  "The Wolf of Wall Street",
  "The Wolverine",
  "The World Is Not Enough",
  "The World's End",
  "The Wrong Trousers",
  "The Zero Theorem",
  "There Will Be Blood",
  "They Live",
  "Thief",
  "Thin Red Line",
  "This Is Spinal Tap",
  "This Is the End",
  "This Means War",
  "Thor",
  "Thor Ragnarok",
  "Thor The Dark World",
  "Thoroughbreds",
  "Threads",
  "Three Colors White",
  "Thunderball",
  "Tickled",
  "Time Bandits",
  "Tinker Tailor Soldier Spy",
  "Titanic",
  "To All the Boys I've Loved Before",
  "To Kill a Mockingbird",
  "To Rome with Love",
  "Togo",
  "Tomb Raider",
  "Tomorrow Never Dies",
  "Tomorrowland",
  "Tootsie",
  "Top Gun",
  "Tora! Tora! Tora!",
  "Total Recall",
  "Toxic Skies",
  "Toy Story",
  "Toy Story 2",
  "Toy Story 3",
  "Toy Story 4",
  "Toy Story That Time Forgot",
  "Traded",
  "Traffik",
  "Training Day",
  "Trainspotting",
  "Trainwreck",
  "Transcendence",
  "Transformers",
  "Transformers Age of Extinction",
  "Transformers Dark of the Moon",
  "Transformers Revenge of the Fallen",
  "Transformers The Last Knight",
  "Trauma Center",
  "Triple 9",
  "Trolls",
  "Trolls World Tour",
  "Tron",
  "TRON Legacy",
  "Tropic Thunder",
  "True Grit",
  "True History of the Kelly Gang",
  "True Lies",
  "True Story",
  "Trumped Inside the Greatest Political Upset of All Time",
  "Truth or Dare",
  "Tully",
  "Tupac Resurrection",
  "Two for the Money",
  "Two-Lane Blacktop",
  "U.S. Marshals",
  "UglyDolls",
  "Ultraviolet",
  "Unbreakable",
  "Uncle Drew",
  "Uncut Gems",
  "Under the Sun",
  "Underwater",
  "Underworld",
  "Underworld Awakening",
  "Underworld Blood Wars",
  "Underworld Evolution",
  "Underworld Rise of the Lycans",
  "Unfaithful",
  "Unfinished Business",
  "Unforgiven",
  "Unfriended",
  "Up",
  "Up in the Air",
  "Up the Creek",
  "Upgrade",
  "Uri The Surgical Strike",
  "Us",
  "V for Vendetta",
  "Valerian and the City of a Thousand Planets",
  "Van Wilder 2 The Rise of Taj",
  "Van Wilder Freshman Year",
  "Vanishing Point",
  "Varsity Blues",
  "Vegas Vacation",
  "Venom",
  "Vertigo",
  "Vice",
  "Victoria",
  "Videodrome",
  "Viral",
  "Virus",
  "Waiting...",
  "Wake in Fright",
  "Walk Hard The Dewey Cox Story",
  "Walk the Line",
  "Wall Street",
  "WALL·E",
  "Waltz with Bashir",
  "War Dogs",
  "War for the Planet of the Apes",
  "War on Everyone",
  "Warcraft",
  "Warm Bodies",
  "Warning Sign",
  "Warrior",
  "Watchmen",
  "Watership Down",
  "Waterworld",
  "We Are Marshall",
  "We're the Millers",
  "Wedding Crashers",
  "Weiner",
  "Welcome to Marwen",
  "West Side Story",
  "What About Bob",
  "What to Expect When You're Expecting",
  "What's Love Got to Do with It",
  "When Harry Met Sally...",
  "When Marnie Was There",
  "Where Eagles Dare",
  "Where the Wild Things Are",
  "While We're Young",
  "Whiplash",
  "Whiskey Tango Foxtrot",
  "Whisper of the Heart",
  "White Boy Rick",
  "White Christmas",
  "Who Framed Roger Rabbit",
  "Who's Afraid of Virginia Woolf",
  "Why Him",
  "Widows",
  "Wild Card",
  "Willy Wonka & the Chocolate Factory",
  "Wind River",
  "Windtalkers",
  "Wish I Was Here",
  "Witness for the Prosecution",
  "Won't You Be My Neighbor",
  "Wonder Woman",
  "Working Girl",
  "World War Z",
  "Wreck-It Ralph",
  "Wuthering Heights",
  "X-Men",
  "X-Men Apocalypse",
  "X-Men Days of Future Past",
  "X-Men First Class",
  "X-Men Origins Wolverine",
  "X-Men The Last Stand",
  "X2",
  "xXx",
  "xXx Return of Xander Cage",
  "xXx State of the Union",
  "Yankee Doodle Dandy",
  "Year One",
  "Yesterday",
  "Yoga Hosers",
  "You Only Live Twice",
  "You Should Have Left",
  "You Were Never Really Here",
  "You've Got Mail",
  "Young Adult",
  "Young Mr. Lincoln",
  "Zero Days",
  "Zodiac",
  "Zombieland",
  "Zombieland Double Tap",
  "Zoolander",
  "Zoolander 2",
  "Zootopia",
]